#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

#define  TIMEOUT     10000UL

/*
SPI_LSB_FIRST
SPI_MSB_FIRST
*/
#define SPI_DATA_ORDER  SPI_LSB_FIRST

/*
SPI_MASTER
SPI_SLAVE 
*/
#define MASTER_SLAVE_SELECT  SPI_MASTER 



/*
SPI_FREQ_DIVIDED_BY_2	
SPI_FREQ_DIVIDED_BY_4	
SPI_FREQ_DIVIDED_BY_8	
SPI_FREQ_DIVIDED_BY_16
SPI_FREQ_DIVIDED_BY_32
SPI_FREQ_DIVIDED_BY_64
SPI_FREQ_DIVIDED_BY_128
*/
#define SPI_CLOCK_RATE  SPI_FREQ_DIVIDED_BY_4



/*
SPI_RISING_LEADING_FALLING_TRAILING
SPI_FALLING_LEADING_RISING_TRAILING
*/   
#define SPI_CLOCK_POLARITY    SPI_RISING_LEADING_FALLING_TRAILING


/*
SPI_SAMPLE_LEADING_SETUP_TRAILING
SPI_SETUP_LEADING_SAMPLE_TRAILING
*/
#define SPI_CLOCK_PHASE  SPI_SAMPLE_LEADING_SETUP_TRAILING



/*
SPI_INTERRUPT_ENABLE 
SPI_INTERRUPT_DISABLE
*/
#define SPI_INTERRUPT_ENABLE_MODE   SPI_INTERRUPT_ENABLE


/*
SPI_ENABLE 
SPI_DISABLE
*/  
#define SPI_ENABLE_MODE    SPI_ENABLE 


#endif
